# Site settings
baseurl = "http://jessed.io/"
languageCode = "en-us"
title = ""
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Jesse Dearing"
	description = "Personal blog of Jesse Dearing discussing programming in Go and JavaScript as well as systems, cloud technologies, and databases."
	bio = "Data - Systems - Code"
	# Enter optionally your twitter account
	twitter = "JesseDearing"
	enableRSS = true

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	#aboutAuthor = "I am a senior site reliability engineer at InVisionApp. I love databases and the technology that make databases run. While I write code mostly in Go, Node, and Ruby I have been known to get into Java, C, and Python to get things done. I love contributing to Open Source. In my free time I like to try microbrews, ride bicycles, and spend time with my family."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/JesseDearing"
    # facebook = ""
    github   = "https://www.github.com/jessedearing"
    # dribble  = ""
